
(()=>{
const C=window.IDP_CORE, P=window.IDP_POSTS, Q=window.IDP_POETRY, R=window.IDP_READER_IMPACT||{entries:[],methodology:''}, V=window.IDP_VERSION_HISTORY||{current:'3.9',releases:[],milestones:[]}, CFG=window.IDP_CONFIG||{};
const app=document.getElementById('app');
const forumById=new Map(C.forums.map(x=>[x.id,x])), topicById=new Map(C.topics.map(x=>[x.id,x])), userById=new Map(C.users.map(x=>[x.id,x])), postById=new Map(P.map(x=>[x.id,x]));
const postsByTopic=new Map(), postsByUser=new Map(), topicsByForum=new Map(), worksByUser=new Map();
for(const p of P){if(!postsByTopic.has(p.t))postsByTopic.set(p.t,[]);postsByTopic.get(p.t).push(p);if(!postsByUser.has(p.u))postsByUser.set(p.u,[]);postsByUser.get(p.u).push(p)}
for(const t of C.topics){if(!topicsByForum.has(t.f))topicsByForum.set(t.f,[]);topicsByForum.get(t.f).push(t)}
for(const w of Q.works){const k=(w.u||'').toLowerCase();if(!worksByUser.has(k))worksByUser.set(k,[]);worksByUser.get(k).push(w)}
const n=x=>Number(x||0).toLocaleString();
let textDisplayMode=localStorage.getItem('idpTextDisplay')||'original';
const mojibakePairs=[['â€™','’'],['â€˜','‘'],['â€œ','“'],['â€','”'],['â€“','–'],['â€”','—'],['â€¦','…'],['â€¢','•'],['Â ',' '],['Ã©','é'],['Ã¨','è'],['Ã¡','á'],['Ã³','ó'],['Ã¶','ö'],['Ã¼','ü'],['Ã±','ñ'],['Ã§','ç'],['Ã¢','â'],['Ãª','ê'],['Ã®','î'],['Ã´','ô'],['Ã»','û'],['Ã£','ã'],['Ãµ','õ'],['Ã¥','å'],['Ã¸','ø'],['Ã¦','æ'],['Ã‰','É']];
function repairMojibake(value){let out=String(value??'');for(const [bad,good] of mojibakePairs)out=out.split(bad).join(good);return out}
function displayText(value){return textDisplayMode==='repair'?repairMojibake(value):String(value??'')}
const esc=s=>displayText(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmtDate(s){if(!s)return 'unknown date';const d=new Date(String(s).replace(' UTC','Z'));return isNaN(d)?esc(s):d.toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:s.length>10?'numeric':undefined,minute:s.length>10?'2-digit':undefined})}
function cleanBB(raw){let s=esc(raw||'');s=s.replace(/\[b(?::[^\]]+)?\]([\s\S]*?)\[\/b(?::[^\]]+)?\]/gi,'<strong>$1</strong>').replace(/\[i(?::[^\]]+)?\]([\s\S]*?)\[\/i(?::[^\]]+)?\]/gi,'<em>$1</em>').replace(/\[u(?::[^\]]+)?\]([\s\S]*?)\[\/u(?::[^\]]+)?\]/gi,'<u>$1</u>').replace(/\[quote(?::[^\]]+)?\]([\s\S]*?)\[\/quote(?::[^\]]+)?\]/gi,'<blockquote>$1</blockquote>').replace(/\[url(?:=[^\]]+)?\]/gi,'').replace(/\[\/url\]/gi,'').replace(/\[(?:img|\/img|size(?:=[^\]]+)?|\/size|color(?:=[^\]]+)?|\/color)(?::[^\]]+)?\]/gi,'').replace(/\r?\n/g,'<br>');return s}
function crumb(items){return `<div class="breadcrumbs">${items.map((x,i)=>i===items.length-1?esc(x[0]):`<a href="${x[1]}">${esc(x[0])}</a> -&gt; `).join('')}</div>`}
function stat(num,label){return `<div class="stat"><b>${n(num)}</b><span>${esc(label)}</span></div>`}
function excerpt(txt,q='',len=220){let s=String(txt||'').replace(/\[[^\]]+\]/g,' ').replace(/\s+/g,' ').trim();if(q){const i=s.toLowerCase().indexOf(q.toLowerCase());if(i>=0)s=s.slice(Math.max(0,i-70),Math.max(0,i-70)+len)}return esc(s.length>len?s.slice(0,len)+'…':s)}
function sectionHead(t,p=''){return `<div class="section-head"><h2>${esc(t)}</h2><p>${esc(p)}</p></div>`}
function pageTitle(k,t,p=''){return `${k?`<div class="eyebrow">${esc(k)}</div>`:''}<h1>${esc(t)}</h1>${p?`<p class="small">${esc(p)}</p>`:''}`}
function routeLink(h,label,cls=''){return `<a class="${cls}" href="${h}">${esc(label)}</a>`}

function home(){
 const s=C.meta.stats; const ev=C.evidence.slice(0,6);
 return `<section class="hero"><div class="hero-main"><div class="eyebrow">Recovered digital community • 2002-2005</div><h1>The message board came back.</h1><p>IDunnoPoetry survives in fragments: poems, usernames, diaries, arguments, jokes, friendships, and the words people left for one another more than twenty years ago.</p><p><a class="btn" href="#forums">Enter the forums</a> <a class="btn secondary" style="border-color:white;color:white" href="#poetry">Browse recovered poetry</a></p></div><aside class="hero-aside"><h2>A museum, not a resurrection</h2><p>This reconstruction preserves historically public material while deliberately leaving private messages, email addresses, IP addresses, passwords, and credentials out of the exhibit.</p><div class="source-note">Built from the union of two contradictory SQL backups. Missing records are treated as missing - never as evidence that something never existed.</div></aside></section>
 <div class="stats">${stat(s.users,'recoverable user IDs')}${stat(s.posts,'surviving public posts')}${stat(s.topics,'surviving topic IDs')}${stat(s.works,'recovered source-level works')}</div>
 ${sectionHead('Explore the archive','Eight ways into the surviving IDP world')}
 <div class="grid"><a class="card" href="#forums"><h3>Message boards</h3><p>Browse recovered forums, topics, and public posts in their original conversational structure.</p></a><a class="card" href="#poetry"><h3>Poetry vault</h3><p>Hundreds of recovered creative records, including historical revisions and community submissions.</p></a><a class="card" href="#people"><h3>People</h3><p>Find an old username and see the public traces that survive: posts, topics, and writing.</p></a><a class="card" href="#timeline"><h3>Timeline</h3><p>Watch recoverable registration and activity grow month by month across the surviving fragments.</p></a><a class="card" href="#search"><h3>Full-text search</h3><p>Search public post text, topic titles, usernames, and recovered poetry in one place.</p></a><a class="card" href="#exhibits"><h3>Guided exhibits</h3><p>Follow the strongest historical stories: growth, creative culture, support, loss, revision, and recovery.</p></a><a class="card" href="#voices"><h3>Reader impact</h3><p>See privacy-safe evidence of long-term readers, emotional support, classroom use, adaptations, and rediscovery.</p></a><a class="card" href="#reclaim"><h3>Reclaim your writing</h3><p>A former member can search an old handle and discover poetry they may have thought was gone.</p></a></div>
 ${sectionHead('Voices from the board','Contemporary statements preserved in public posts')}
 <div class="grid">${ev.map(e=>`<div class="card quote-card"><span class="pill gold">${esc(String(e.category).replaceAll('_',' '))}</span><q>${excerpt(e.excerpt,'',180)}</q><cite>${esc(e.username)} • ${esc(e.forum)} • ${fmtDate(e.date_utc)}</cite><p class="small"><a href="#topic/${topicForEvidence(e.post_id)}">Open context</a></p></div>`).join('')}</div>
 <div class="callout" style="margin-top:28px"><strong>Scale clue:</strong> only ${n(s.posts)} public post IDs survive, while later member counters total ${n(s.member_counter_sum)} posts and assigned post IDs reach ${n(s.max_post_id)}. The museum therefore shows fragments of a substantially larger historical board.</div>`
}
function topicForEvidence(pid){const p=P.find(x=>x.id===Number(pid));return p?p.t:''}

function firstPostForTopic(t){const direct=postById.get(Number(t?.first));if(direct)return direct;const ps=(postsByTopic.get(Number(t?.id))||[]).slice().sort((a,b)=>String(a.d).localeCompare(String(b.d)));return ps[0]||null}
function lastPostForTopic(t){const direct=postById.get(Number(t?.last));if(direct)return direct;const ps=(postsByTopic.get(Number(t?.id))||[]).slice().sort((a,b)=>String(a.d).localeCompare(String(b.d)));return ps[ps.length-1]||null}
function lastPostForForum(f){let best=null,bestTopic=null;for(const t of (topicsByForum.get(Number(f?.id))||[])){const p=lastPostForTopic(t);if(p&&(!best||String(p.d)>String(best.d))){best=p;bestTopic=t}}return best?{p:best,t:bestTopic}:null}
function userLinkForPost(p){if(!p)return '<span class="muted">unknown</span>';const u=userById.get(Number(p.u));const name=p.n||u?.n||'Anonymous';return u?`<a href="#user/${u.id}">${esc(name)}</a>`:esc(name)}
const threadStarterMap=window.IDP_THREAD_STARTERS||{};
function topicStarterUser(t){const uid=Number(threadStarterMap[String(t?.id)]||0);if(uid){const u=userById.get(uid);if(u)return u}const p=firstPostForTopic(t);if(!p)return null;return userById.get(Number(p.u))||{id:Number(p.u)||0,n:p.n||'Anonymous'}}
function topicStarterLink(t){const u=topicStarterUser(t);if(!u)return '<span class="muted">unknown</span>';return u.id&&userById.has(Number(u.id))?`<a href="#user/${u.id}">${esc(u.n)}</a>`:esc(u.n||'Anonymous')}
function topicStarterName(t){return topicStarterUser(t)?.n||'unknown'}
function topicLastPage(t){return Math.max(1,Math.ceil((postsByTopic.get(Number(t?.id))||[]).length/20))}
function latestReplyLink(t,label='Go to last surviving post'){const page=topicLastPage(t);return `<a class="mini-last-link" href="#topic/${t.id}/${page}" title="${esc(label)}"><img class="latest-reply-icon" src="assets/subsilver/icon_latest_reply.gif" alt="" aria-hidden="true"><span class="latest-reply-fallback">›</span></a>`}
function lastPostCell(t){const p=lastPostForTopic(t);if(!p)return '<span class="muted">not recovered</span>';return `${fmtDate(p.d)}<br>${userLinkForPost(p)} ${latestReplyLink(t)}`}

function forums(){
 const cats={};for(const f of C.forums){(cats[f.cat]??=[]).push(f)}
 let html=pageTitle('Forum Index','I Dunno Poetry','The surviving messageboard structure reconstructed from the public SQL snapshots.');
 html+=`<div class="forum-footerline"><b>${n(C.meta.stats.posts)}</b> surviving public posts • <b>${n(C.meta.stats.topics)}</b> surviving topics • <b>${n(C.meta.stats.users)}</b> recoverable member IDs</div>`;
 for(const [cat,fs] of Object.entries(cats)){
   html+=`<section class="forum-category"><div class="cat-title">${esc(cat)}<span class="cat-meta">${fs.length} surviving forum${fs.length===1?'':'s'}</span></div><div class="forum-table-head"><span></span><span>Forum</span><span>Topics</span><span>Posts</span><span>Last post</span></div>${fs.sort((a,b)=>b.sp-a.sp).map(f=>{const lp=lastPostForForum(f);return `<div class="forum-row"><div><span class="forum-icon" aria-hidden="true"></span></div><div class="forum-main"><a href="#forum/${f.id}">${esc(f.n)}</a><div class="desc">Recovered from ${esc(f.p)}</div></div><div class="count-cell">${n(f.st)}</div><div class="count-cell">${n(f.sp)}</div><div class="last-cell">${lp?`${fmtDate(lp.p.d)}<br>${userLinkForPost(lp.p)} ${latestReplyLink(lp.t,'Go to last surviving post in this forum')}`:'<span class="muted">not recovered</span>'}</div></div>`}).join('')}</section>`;
 }
 const newest=C.users.slice().sort((a,b)=>String(b.d).localeCompare(String(a.d)))[0];
 html+=`<div class="classic-index-footer"><section class="classic-stats"><div class="classic-box-title">Statistics</div><div class="classic-box-body">Surviving archive: <b>${n(C.meta.stats.posts)}</b> public posts in <b>${n(C.meta.stats.topics)}</b> topics.<br>Recoverable member IDs: <b>${n(C.meta.stats.users)}</b>.${newest?` Latest recoverable registration: <a href="#user/${newest.id}">${esc(newest.n)}</a> (${fmtDate(newest.d)}).`:''}</div></section><section class="classic-icon-key"><div class="classic-box-title">Historical subSilver icon key</div><div class="classic-box-body icon-key-row"><span><img src="assets/subsilver/folder_big.gif" alt=""> No new posts</span><span><img src="assets/subsilver/folder_new_big.gif" alt=""> New posts</span><span><img src="assets/subsilver/folder_locked_big.gif" alt=""> Forum locked</span></div><div class="classic-key-note">Visual reference only: the museum is read-only and does not recreate viewer-specific unread state.</div></section></div><div class="forum-footerline">Archive index • historical phpBB categories preserved where recoverable • counts reflect surviving records, not original totals</div>`;
 return html;
}
function forum(id,page=1){
 const f=forumById.get(Number(id));if(!f)return missing('Forum');
 const all=(topicsByForum.get(f.id)||[]).slice().sort((a,b)=>String(b.d).localeCompare(String(a.d)));
 page=Math.max(1,Number(page)||1);const per=20,pages=Math.max(1,Math.ceil(all.length/per));if(page>pages)page=pages;const ts=all.slice((page-1)*per,page*per);
 return `${crumb([['Forum Index','#forums'],[f.n]])}${pageTitle(f.cat,f.n,`${n(f.sp)} surviving posts • ${n(f.st)} surviving topics • page ${page} of ${pages}`)}${pager(`#forum/${f.id}/`,page,pages)}<div class="topic-table"><div class="topic-table-head"><span></span><span>Topics</span><span>Replies</span><span>Author</span><span>Views</span><span>Last post</span></div>${ts.length?ts.map(t=>{const fp=firstPostForTopic(t);return `<div class="topic-row"><div><span class="topic-icon" aria-hidden="true"></span></div><div class="topic-main"><a href="#topic/${t.id}">${esc(t.title)}</a><div class="desc"><strong>Started by ${topicStarterLink(t)}</strong> • topic #${n(t.id)} • ${esc(t.p)}</div></div><div class="count-cell">${n(t.r)}</div><div class="author-cell">${topicStarterLink(t)}</div><div class="count-cell">${n(t.v)}</div><div class="last-cell">${lastPostCell(t)}</div></div>`}).join(''):'<div class="empty">No surviving topics.</div>'}</div>${pager(`#forum/${f.id}/`,page,pages)}<div class="forum-footerline"><a href="#forums">Forum Index</a> -&gt; ${esc(f.n)} • 20 topics per page, matching the preserved IDP phpBB configuration • read-only museum reconstruction.</div>`
}
function topic(id,page=1){
 const t=topicById.get(Number(id));if(!t)return missing('Topic');const f=forumById.get(t.f);const all=(postsByTopic.get(t.id)||[]).slice().sort((a,b)=>String(a.d).localeCompare(String(b.d)));
 page=Math.max(1,Number(page)||1);const per=20,pages=Math.max(1,Math.ceil(all.length/per));if(page>pages)page=pages;const start=(page-1)*per,ps=all.slice(start,start+per);
 const siblings=(topicsByForum.get(t.f)||[]).slice().sort((a,b)=>String(a.d).localeCompare(String(b.d)));const si=siblings.findIndex(x=>x.id===t.id);const older=si>0?siblings[si-1]:null,newer=si>=0&&si<siblings.length-1?siblings[si+1]:null;
 return `${crumb([['Forum Index','#forums'],[f?f.n:'Forum',f?`#forum/${f.id}`:'#forums'],[t.title]])}${pageTitle('Recovered topic',t.title,`${all.length} surviving post${all.length===1?'':'s'} • started by ${displayText(topicStarterName(t))} • ${f?f.n:''} • page ${page} of ${pages}`)}${pager(`#topic/${t.id}/`,page,pages)}<div class="topic-prevnext"><span>${older?`<a href="#topic/${older.id}">View previous topic</a>`:'View previous topic'}</span><span>${newer?`<a href="#topic/${newer.id}">View next topic</a>`:'View next topic'}</span></div><div class="callout"><strong>Snapshot note:</strong> topic reply/view counters can exceed the posts visible here because the backups were already incomplete when preserved.</div><div class="post-columns-head"><span>Author</span><span>Message</span></div>${ps.map((p,i)=>postCard(p,start+i+1)).join('')}${pager(`#topic/${t.id}/`,page,pages)}${crumb([['Forum Index','#forums'],[f?f.n:'Forum',f?`#forum/${f.id}`:'#forums'],[t.title]])}`
}
function postCard(p,num){
 const u=userById.get(p.u);const uname=p.n||u?.n||'Anonymous';
 return `<article class="post" id="post-${p.id}"><div class="post-topline"><span><img class="mini-post-icon" src="assets/subsilver/icon_minipost.gif" alt="" aria-hidden="true"><b>Posted:</b> ${fmtDate(p.d)}</span><span><b>Post #${num}</b> • id ${n(p.id)} • ${esc(p.p)}</span></div><aside class="post-author"><div class="username"><a href="#user/${p.u}">${esc(uname)}</a></div>${u?`<dl><dt>Joined:</dt><dd>${fmtDate(u.d)}</dd><dt>Historical posts:</dt><dd>${n(u.pc)}</dd><dt>Surviving posts:</dt><dd>${n(u.sp)}</dd><dt>User ID:</dt><dd>${n(u.id)}</dd></dl>`:`<div class="small">Historical account record not recovered.</div>`}</aside><div class="post-message">${p.s?`<div class="kicker">Post subject: ${esc(p.s)}</div>`:''}${cleanBB(p.x)}</div></article>`
}
function people(){return `${pageTitle('Directory','People','Historical public usernames only; no email addresses or private profile data are displayed.')}<div class="directory-tools"><input id="peopleFilter" type="search" placeholder="Filter usernames…" aria-label="Filter usernames"><select id="peopleSort"><option value="posts">Most historical posts</option><option value="survive">Most surviving posts</option><option value="name">Username A-Z</option><option value="date">Earliest registration</option></select></div><div id="peopleRows" class="people-list"></div>`}
function mountPeople(){const input=document.getElementById('peopleFilter'), sort=document.getElementById('peopleSort'), out=document.getElementById('peopleRows');if(!out)return;function draw(){let q=(input.value||'').toLowerCase();let a=C.users.filter(u=>!q||u.n.toLowerCase().includes(q));const mode=sort.value;a.sort((x,y)=>mode==='name'?x.n.localeCompare(y.n):mode==='date'?String(x.d).localeCompare(String(y.d)):mode==='survive'?y.sp-x.sp:y.pc-x.pc);out.innerHTML=a.slice(0,500).map(u=>`<div class="row"><div><a href="#user/${u.id}">${esc(u.n)}</a><div class="sub">Registered ${fmtDate(u.d)} • user ID ${u.id}</div></div><div class="counts">${n(u.pc)} profile counter<br>${n(u.sp)} surviving posts</div></div>`).join('')+(a.length>500?`<div class="empty">Showing 500 of ${n(a.length)} matches. Narrow the filter to see more.</div>`:'')}
input.addEventListener('input',draw);sort.addEventListener('change',draw);draw()}
function user(id,page=1){const u=userById.get(Number(id));if(!u)return missing('User');const ups=(postsByUser.get(u.id)||[]).slice().sort((a,b)=>String(b.d).localeCompare(String(a.d)));const ws=worksByUser.get((u.n||'').toLowerCase())||[];page=Math.max(1,Number(page)||1);const per=100,pages=Math.max(1,Math.ceil(ups.length/per)),slice=ups.slice((page-1)*per,page*per);return `${crumb([['People','#people'],[u.n]])}${pageTitle('Historical public profile',u.n,`User ID ${u.id} • registered ${fmtDate(u.d)}`)}<div class="stats">${stat(u.pc,'historical profile post counter')}${stat(u.sp,'surviving public posts')}${stat(ws.length,'recovered creative works')}${stat(ups.length,'public posts in museum union')}</div>${ws.length?sectionHead('Recovered writing',`${ws.length} selected source records`)+`<div class="work-list">${ws.slice().sort((a,b)=>String(b.d).localeCompare(String(a.d))).map(workRow).join('')}</div>`:''}${sectionHead('Surviving public posts',`Newest first • page ${page} of ${pages}`)}${slice.map(p=>{const t=topicById.get(p.t);return `<article class="post"><header class="post-head"><span>${fmtDate(p.d)} • ${t?`<a href="#topic/${t.id}">${esc(t.title)}</a>`:'topic unavailable'}</span><span>post ${n(p.id)}</span></header><div class="post-body">${excerpt(p.x,'',650)}</div></article>`}).join('')||'<div class="empty">No surviving public posts.</div>'}${pager(`#user/${u.id}/`,page,pages)}`}
function pager(prefix,page,pages){if(pages<=1)return '';let out='<nav class="pagination" aria-label="Pagination">';for(let i=1;i<=pages;i++){if(i===1||i===pages||Math.abs(i-page)<=2)out+=`<a class="${i===page?'current':''}" href="${prefix}${i}">${i}</a>`;else if(i===page-3||i===page+3)out+='<span>…</span>'}return out+'</nav>'}

function poetry(){return `${pageTitle('Creative archive','Poetry','Recovered source records from the main poetry database and poetry-forum threads. Reposts and revisions are preserved rather than silently erased.')}<div class="directory-tools"><input id="poetryFilter" type="search" placeholder="Filter title, username, or credit…" aria-label="Filter poetry"><select id="poetrySource"><option value="all">All sources</option><option value="main_site_brandon">Brandon main archive</option><option value="main_site_community">Community submissions</option><option value="forum_poetry_thread">Forum poetry</option></select></div><div id="poetryRows" class="work-list"></div>`}
function workRow(w){return `<div class="row"><div><a href="#poem/${w.id}">${esc(w.title)}</a><div class="sub">${esc(w.u||w.credit||'Unknown')} • ${fmtDate(w.d)} • ${esc(w.forum||w.type)}</div></div><div class="counts">${w.vc>1?`${w.vc} versions<br>`:''}${esc(w.conf||'')}</div></div>`}
function mountPoetry(){const input=document.getElementById('poetryFilter'),src=document.getElementById('poetrySource'),out=document.getElementById('poetryRows');if(!out)return;function draw(){const q=(input.value||'').toLowerCase(),s=src.value;let a=Q.works.filter(w=>(s==='all'||w.type===s)&&(!q||(w.title+' '+w.u+' '+w.credit).toLowerCase().includes(q)));out.innerHTML=a.slice(0,600).map(workRow).join('')+(a.length>600?`<div class="empty">Showing 600 of ${n(a.length)} matches. Narrow the filter.</div>`:'')||'<div class="empty">No matching recovered works.</div>'}input.addEventListener('input',draw);src.addEventListener('change',draw);draw()}
function poem(id){const w=Q.works[Number(id)];if(!w)return missing('Poem');const vs=Q.versions[String(w.id)]||[];const topic=w.topic?topicById.get(Number(w.topic)):null;const comments=topic?(postsByTopic.get(topic.id)||[]).filter(p=>String(p.id)!==String(w.post)):[];return `${crumb([['Poetry','#poetry'],[w.title]])}${pageTitle(w.type.replaceAll('_',' '),w.title,`${esc(w.u||w.credit||'Unknown')} • ${fmtDate(w.d)}`)}<div class="poem-shell"><pre class="poem-text">${esc(w.x)}</pre><aside class="side-card"><dl><dt>Username</dt><dd>${w.u?userLinkByName(w.u):'unknown'}</dd>${w.credit&&w.credit!==w.u?`<dt>Published credit</dt><dd>${esc(w.credit)}</dd>`:''}<dt>Source</dt><dd>${esc(w.forum||w.type)}</dd><dt>Confidence</dt><dd>${esc(w.conf||'')}</dd><dt>Versions preserved</dt><dd>${n(w.vc)}</dd>${topic?`<dt>Original topic</dt><dd><a href="#topic/${topic.id}">${esc(topic.title)}</a></dd>`:''}</dl></aside></div>${vs.length>1?sectionHead('Preserved versions',`${vs.length} database snapshots/versions`)+`<div class="grid">${vs.map(v=>`<div class="card"><h3>${esc(v.snapshot)}</h3><p>${esc(v.title)} • ${fmtDate(v.d)}</p><details><summary>Read this version</summary><pre class="poem-text" style="font-size:14px;margin-top:10px">${esc(v.x)}</pre></details></div>`).join('')}</div>`:''}${comments.length?sectionHead('Original reactions',`${comments.length} surviving replies in the topic`)+comments.map((p,i)=>postCard(p,i+1)).join(''):''}`}
function userIdForName(name){const u=C.users.find(x=>x.n.toLowerCase()===String(name).toLowerCase());return u?u.id:null}
function userLinkByName(name){const id=userIdForName(name);return id===null?esc(name):`<a href="#user/${id}">${esc(name)}</a>`}

function timeline(){const rows=C.timeline.filter(x=>String(x.month)<='2005-02');const maxR=Math.max(...rows.map(x=>Number(x.registrations)||0)),maxP=Math.max(...rows.map(x=>Number(x.surviving_public_posts_union)||0));return `${pageTitle('Chronology','Timeline','Month-by-month evidence from recoverable registrations and public records. Surviving post counts are incomplete fragments, not traffic analytics.')}<div class="callout"><strong>Archive range:</strong> recoverable registrations begin Oct. 19, 2002; surviving forum activity reaches Feb. 13, 2005; the main poetry table continued through Apr. 4, 2011.</div><div class="timeline" style="margin-top:24px">${rows.map(r=>`<div class="time-item"><strong>${esc(r.month)}</strong><div class="small">${n(r.registrations)} registrations • ${n(r.cumulative_registered_users_recoverable)} cumulative recoverable IDs • ${n(r.surviving_topics_union)} surviving topics</div><div class="bars"><div class="barline"><span>registrations</span><div class="bar"><i style="width:${(Number(r.registrations)||0)/maxR*100}%"></i></div><b>${n(r.registrations)}</b></div><div class="barline"><span>surviving posts</span><div class="bar"><i style="width:${(Number(r.surviving_public_posts_union)||0)/maxP*100}%"></i></div><b>${n(r.surviving_public_posts_union)}</b></div></div></div>`).join('')}</div>`}

function search(q=''){q=decodeURIComponent(q||'');let html=pageTitle('Archive-wide','Search','Search public posts, topic titles, usernames, and recovered poetry.');html+=`<form class="searchbox" id="searchForm"><input id="searchInput" value="${esc(q)}" type="search" placeholder="Try a username, phrase, poem title…"><button class="btn">Search</button></form>`;if(!q)return html+'<div class="empty">Enter at least two characters.</div>';if(q.length<2)return html+'<div class="empty">Please use at least two characters.</div>';const low=q.toLowerCase();const us=C.users.filter(u=>u.n.toLowerCase().includes(low)).slice(0,30),ts=C.topics.filter(t=>t.title.toLowerCase().includes(low)).slice(0,40),ws=Q.works.filter(w=>(w.title+' '+w.u+' '+w.credit+' '+w.x).toLowerCase().includes(low)).slice(0,60),ps=P.filter(p=>(p.n+' '+p.s+' '+p.x).toLowerCase().includes(low)).slice(0,120);html+=`<div class="stats">${stat(us.length,'username matches shown')}${stat(ts.length,'topic-title matches shown')}${stat(ws.length,'poetry matches shown')}${stat(ps.length,'public-post matches shown')}</div>`;if(us.length)html+=sectionHead('People')+`<div class="people-list">${us.map(u=>`<div class="row"><div><a href="#user/${u.id}">${esc(u.n)}</a></div><div class="counts">${n(u.pc)} profile counter</div></div>`).join('')}</div>`;if(ts.length)html+=sectionHead('Topics')+`<div class="topic-list">${ts.map(t=>{const fp=firstPostForTopic(t);return `<div class="row"><div><a href="#topic/${t.id}">${esc(t.title)}</a><div class="sub">Started by ${topicStarterLink(t)} • ${esc(forumById.get(t.f)?.n||'')}</div></div><div class="counts">${n(t.r)} replies</div></div>`}).join('')}</div>`;if(ws.length)html+=sectionHead('Poetry')+`<div class="work-list">${ws.map(workRow).join('')}</div>`;if(ps.length)html+=sectionHead('Public posts',`Showing first ${ps.length} matches`)+ps.map(p=>{const t=topicById.get(p.t);return `<article class="post"><header class="post-head"><span><a href="#user/${p.u}">${esc(p.n)}</a> • ${fmtDate(p.d)}</span><span>${t?`<a href="#topic/${t.id}">${esc(t.title)}</a>`:''}</span></header><div class="post-body">${excerpt(p.x,q,360)}</div></article>`}).join('');return html}
function mountSearch(q){const form=document.getElementById('searchForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const v=document.getElementById('searchInput').value.trim();location.hash='#search/'+encodeURIComponent(v)})}

function reclaim(q=''){q=decodeURIComponent(q||'');let matched=[];if(q){const low=q.toLowerCase();matched=Q.works.filter(w=>(w.u+' '+w.credit).toLowerCase().includes(low));}
 return `${pageTitle('Lost-and-found writing','Reclaim your poems','If you remember an IDP username or published credit, search it here. The museum exposes no historical email address; identity verification can happen privately with the archive owner.')}<div class="callout"><strong>Why this exists:</strong> many contributors probably do not possess their early-2000s writing anymore. The recovery bundles were designed so one person’s work can be returned without handing over the raw database or anybody else’s private data.</div><form class="searchbox" id="reclaimForm"><input id="reclaimInput" value="${esc(q)}" type="search" placeholder="Old username or author credit"><button class="btn">Find writing</button></form>${q?(matched.length?`<div class="work-list">${matched.slice(0,300).map(workRow).join('')}</div>`:'<div class="empty">No recovered creative records match that name. Try a partial username.</div>'):`<div class="panel"><h2>How reclamation works</h2><ol><li>Search an old username, handle, or published author credit.</li><li>Open the recovered works and confirm that the material is yours.</li><li>Contact the archive owner through <a href="${esc(CFG.contactUrl||'#')}" target="_blank" rel="noopener">${esc(CFG.siteLabel||'the archive site')}</a>. Historical contact data can be used privately for corroboration where appropriate, but is never published.</li><li>The person can receive their own recovered bundle, including older versions when preserved.</li></ol></div>`}`}
function mountReclaim(){const f=document.getElementById('reclaimForm');if(f)f.addEventListener('submit',e=>{e.preventDefault();location.hash='#reclaim/'+encodeURIComponent(document.getElementById('reclaimInput').value.trim())})}

function readerImpact(){
 const entries=(R.entries||[]).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));
 const longTerm=entries.filter(e=>e.category==='long_term_reader').length;
 const applied=entries.filter(e=>e.category==='education'||e.category==='adaptation').length;
 const privateCount=entries.filter(e=>!e.public).length;
 const label=x=>String(x||'reader evidence').replaceAll('_',' ');
 return `${pageTitle('Independent contemporary evidence','Reader Impact','Privacy-safe summaries of surviving correspondence and public interaction records showing how people used, remembered, and responded to IDunnoPoetry.')}
 <div class="callout"><strong>Evidence standard:</strong> these records document individual experiences; they do <em>not</em> establish a total audience size. Private correspondence is anonymized and paraphrased. Raw emails, addresses, IPs, and message identifiers are not published here.</div>
 <div class="stats">${stat(entries.length,'documented impact records')}${stat('2005','earliest surviving correspondence')}${stat(longTerm,'long-term readership records')}${stat(applied,'education / adaptation records')}</div>
 <div class="panel"><h2>What the correspondence adds</h2><p>The forum database can show posts, users, and poems. Correspondence shows what happened beyond those tables: readers returning after years, people using poems in school and teaching, song and social-media adaptations, and readers describing the writing as a source of identification or support.</p><p>Two especially strong chronology clues are independent: a March 2006 correspondent said they had followed the poetry for about four years, implying readership around 2002; a March 2015 correspondent said they first discovered IDunnoPoetry in 2003 and rediscovered it nearly twelve years later.</p></div>
 ${sectionHead('Surviving reader evidence',`${entries.length} privacy-safe records • ${privateCount} derived from private correspondence`)}
 <div class="grid">${entries.map(e=>`<article class="card impact-card"><div><span class="pill gold">${esc(e.date.slice(0,4))}</span><span class="pill">${esc(label(e.category))}</span></div><h3>${esc(e.related_work||'IDunnoPoetry')}</h3><p>${esc(e.summary)}</p><div class="source-note"><strong>Source class:</strong> ${esc(e.channel)} • ${e.public?'public interaction':'private correspondence, paraphrased'}</div></article>`).join('')}</div>
 <div class="source-note"><strong>Methodology:</strong> ${esc(R.methodology||'Private correspondence is summarized without publishing identifying information or raw message text.')}</div>`
}
function exhibits(){
 const s=C.meta.stats;const positive=C.evidence.filter(e=>String(e.category).toLowerCase()!=='counterevidence').slice(0,5);const counter=C.evidence.find(e=>String(e.category).toLowerCase()==='counterevidence');
 return `${pageTitle('Guided history','Museum Exhibits','Curated paths through the recovered record. Verified database evidence, archival inference, and creator recollection remain explicitly separate.')}
 <section class="forum-category"><div class="cat-title">01 · Before the Feed</div><div class="panel"><h2>A social network organized around writing</h2><p>IDunnoPoetry’s recoverable registrations begin in October 2002. The preserved board contains ${n(s.users)} user IDs, ${n(s.topics)} topic IDs, and 60 forum structures spanning poetry, diaries, advice, debate, music, images, games, and ordinary conversation.</p><p><a href="#forums">Walk the reconstructed forum index →</a></p></div></section>
 <section class="forum-category"><div class="cat-title">02 · Words Became Social Infrastructure</div><div class="panel"><h2>Poems did not sit alone</h2><p>The recovery identified ${n(s.works)} source-level creative records and ${n(s.poetry_comments)} surviving replies to poetry threads. The writing survives together with fragments of its original audience: encouragement, interpretation, jokes, arguments, and friendship.</p><p><a href="#poetry">Browse the poetry vault →</a></p></div></section>
 <section class="forum-category"><div class="cat-title">03 · Support, Belonging — and the Counterevidence</div><div class="grid">${positive.map(e=>`<div class="card quote-card"><q>${excerpt(e.excerpt,'',190)}</q><cite>${esc(e.username)} • ${fmtDate(e.date_utc)}</cite></div>`).join('')}${counter?`<div class="card danger-callout"><h3>Necessary counterpoint</h3><p>${excerpt(counter.excerpt,'',230)}</p><div class="meta">${esc(counter.username)} • ${fmtDate(counter.date_utc)}</div></div>`:''}</div></section>
 <section class="forum-category"><div class="cat-title">04 · Revision Archaeology</div><div class="panel"><h2>The poems themselves changed</h2><p>The early backup contains 143 Brandon poem IDs. Of those, 97 differ in title or text in the later snapshot. The database therefore preserves a genuine writing-development record rather than merely duplicate copies.</p><p><a href="#poetry">Explore recovered works and versions →</a></p></div></section>
 <section class="forum-category"><div class="cat-title">05 · The Missing Majority</div><div class="panel"><h2>${n(s.posts)} surviving posts are only the wreckage</h2><p>Later member profile counters total ${n(s.member_counter_sum)} posts, while assigned post IDs reach ${n(s.max_post_id)}. Those independent signals indicate that most of the historical forum is gone. The museum treats absence as loss, not proof that something never happened.</p><p><a href="#timeline">See the surviving chronology →</a></p></div></section>
 <section class="forum-category"><div class="cat-title">06 · The Interface Time Capsule</div><div class="panel"><h2>phpBB 2.0.6, subSilver, skyLineGrey, Helius</h2><p>The database preserves the forum engine version and style configuration. subSilver was the board default; skyLineGrey and Helius were also installed. Use the style selector above to move between the three historically documented looks. The modern skin is deliberately separate. This build restores the core subSilver gradient cells, forum/topic folder graphics, and mini-post marker from surviving phpBB2 source assets; Helius and skyLineGrey remain configuration-based reconstructions until their exact binary packs can be verified and ingested.</p><p>The preserved phpBB configuration also specifies 20 topics per page and 20 posts per page; this reconstruction now reproduces those original page lengths. The public archive also preserves the community talking about those styles: <a href="#topic/5015">“new board styles” (Nov. 2003)</a> and <a href="#topic/5962">“Which template do you use?” (Jan. 2004)</a>.</p></div></section>
 <section class="forum-category"><div class="cat-title">07 · Lost-and-Found Literature</div><div class="panel"><h2>The archive can return work to its authors</h2><p>Community submissions and forum poetry remain indexed by historical public username or credited author. The reclamation workflow is designed to return one person’s recovered public writing without exposing the raw database or somebody else’s private data.</p><p><a href="#reclaim">Search an old username →</a></p></div></section>
 <section class="forum-category"><div class="cat-title">08 · Beyond the Database</div><div class="panel"><h2>Readers left evidence outside the forum</h2><p>Surviving correspondence documents people returning after years, describing emotional impact, using poems in school and teaching, adapting lines into other media, and tracing their readership back to the early IDP years. Private messages are represented only through anonymized paraphrase.</p><p><a href="#voices">Explore Reader Impact →</a></p></div></section>`
}

function versionHistory(){
 const releases=(V.releases||[]);const milestones=(V.milestones||[]);
 const confirmed=releases.filter(x=>x.status==='confirmed'||x.status==='current').length;
 return `${pageTitle('Build provenance','Version History',`Current public version: v${esc(V.current||CFG.version||'3.9')}. This page distinguishes confirmed release markers from development intervals whose exact numbering cannot be recovered.`)}
 <div class="stats">${stat(releases.length,'version entries')}${stat(confirmed,'confirmed/current markers')}${stat(milestones.length,'documented build milestones')}${stat(V.current||CFG.version||'3.9','current version')}</div>
 <div class="callout"><strong>Why there is a gap:</strong> the repository explicitly records v3.3, the historical README explicitly records v3.4, and the current museum is v3.9. No reliable repository evidence maps individual changes to v3.5, v3.6, v3.7, or v3.8, so those releases are not reconstructed by assumption.</div>
 ${sectionHead('Confirmed release markers','Evidence-backed labels only')}
 <div class="grid">${releases.map(x=>`<article class="card"><div><span class="pill ${x.status==='current'?'gold':''}">v${esc(x.version)}</span><span class="pill">${esc(x.status)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="source-note"><strong>Evidence:</strong> ${esc(x.evidence)} • ${esc(x.date)}</div></article>`).join('')}</div>
 ${sectionHead('Build milestones','Repository chronology on September 23, 2026')}
 <div class="timeline">${milestones.map(m=>`<div class="time-item"><strong>${esc(m.time)} · ${esc(m.title)}</strong><div class="small">${esc(m.detail)}</div></div>`).join('')}</div>
 <div class="source-note">Earlier Lovable-side revisions may predate this Git repository. This page records only version evidence that can presently be substantiated.</div>`
}
function about(){return `${pageTitle('Method & ethics','About the reconstruction','What the museum can prove, what it can infer, and what it deliberately refuses to expose.')}<div class="grid"><div class="card"><h3>Two snapshots, one union</h3><p>The earlier backup is stronger for the 2003-2004 community; the later backup preserves later posts and an expanded poetry archive. The museum merges both and retains provenance.</p></div><div class="card"><h3>Historically grounded interface</h3><p>The surviving configuration identifies phpBB 2.0.6, with subSilver as the default style and skyLineGrey plus Helius also installed. It also preserves the original 20-topics-per-page and 20-posts-per-page settings, which the museum reproduces. The subSilver skin now uses surviving phpBB2 gradient and folder/minipost assets; Helius and skyLineGrey remain evidence-backed CSS reconstructions pending exact-pack verification. The modern museum skin remains deliberately separate.</p></div><div class="card"><h3>Privacy by construction</h3><p>No email addresses, IP addresses, password data, or private-message bodies are included in this website’s data files. Reader Impact entries derived from private correspondence are anonymized paraphrases; the original messages remain outside the public museum.</p></div><div class="card"><h3>Text display is reversible</h3><p>The header toggle can repair common mojibake such as â€™ for readability. The original recovered strings remain unchanged in the archive data, and the default display is the original text.</p></div></div>${sectionHead('The scale problem')}<div class="panel"><p>The museum contains <strong>${n(C.meta.stats.posts)}</strong> distinct surviving public posts. The later member post counters total about <strong>${n(C.meta.stats.member_counter_sum)}</strong>, and assigned post IDs reach <strong>${n(C.meta.stats.max_post_id)}</strong>. Those signals support an order-of-magnitude conclusion that the historical board once held roughly one hundred thousand public posts, but they do not produce an exact historical total.</p></div>${sectionHead('Search-bar mystery')}<div class="panel"><p>The huge <code>phpbb_search_wordmatch</code> table in the raw database is a full-text index, not a record of what people typed into the search box. Only a handful of cached search-result rows survive, and they do not preserve the query text. The backups therefore cannot identify or quantify the remembered repeated arbitrary searches.</p></div>${sectionHead('Publishing standard')}<div class="danger-callout callout"><strong>Do not upload the original SQL dumps.</strong> They contain material that does not belong in a public museum. Publish this sanitized reconstruction instead.</div><p class="source-note">Reconstruction date: ${esc(C.meta.built)}. Archive owner: ${esc(CFG.archiveOwner||'IDunnoPoetry')}. <a href="#versions">View version history.</a></p>`}
function missing(thing){return `${pageTitle('Archive gap',thing+' not found')}<div class="empty">That record is not present in the recovered union.</div>`}

function render(){const h=(location.hash||'#home').slice(1);const parts=h.split('/');const key=parts[0]||'home';let html='';switch(key){case'home':html=home();break;case'forums':html=forums();break;case'forum':html=forum(parts[1],parts[2]);break;case'topic':html=topic(parts[1],parts[2]);break;case'people':html=people();break;case'user':html=user(parts[1],parts[2]);break;case'poetry':html=poetry();break;case'poem':html=poem(parts[1]);break;case'timeline':html=timeline();break;case'exhibits':html=exhibits();break;case'voices':html=readerImpact();break;case'versions':html=versionHistory();break;case'search':html=search(parts.slice(1).join('/'));break;case'reclaim':html=reclaim(parts.slice(1).join('/'));break;case'about':html=about();break;default:html=missing('Page')}app.innerHTML=html;window.scrollTo(0,0);app.focus({preventScroll:true});if(key==='people')mountPeople();if(key==='poetry')mountPoetry();if(key==='search')mountSearch(parts.slice(1).join('/'));if(key==='reclaim')mountReclaim()}
window.addEventListener('hashchange',render);
const skinSelect=document.getElementById('skinSelect');
const skins=['subsilver','skyline','helius','museum'];
function applySkin(name){const skin=skins.includes(name)?name:'subsilver';document.body.classList.remove(...skins.map(x=>'skin-'+x));document.body.classList.add('skin-'+skin);if(skinSelect)skinSelect.value=skin;localStorage.setItem('idpSkin',skin)}
applySkin(localStorage.getItem('idpSkin')||'subsilver');
if(skinSelect)skinSelect.addEventListener('change',()=>applySkin(skinSelect.value));
const textDisplaySelect=document.getElementById('textDisplaySelect');
if(textDisplaySelect){textDisplaySelect.value=textDisplayMode;textDisplaySelect.addEventListener('change',()=>{textDisplayMode=textDisplaySelect.value==='repair'?'repair':'original';localStorage.setItem('idpTextDisplay',textDisplayMode);render()})}
const notice=document.getElementById('notice');if(localStorage.getItem('idpNotice')==='dismissed')notice.style.display='none';document.getElementById('dismissNotice').addEventListener('click',()=>{notice.style.display='none';localStorage.setItem('idpNotice','dismissed')});render();
})();
